# Packaging format v2 (YunoHost ≥ 11.1)
packaging_format = 2
id = "gnuhealth-thalamus"
name = "GNU Health Thalamus"
description.en = "GNU Health Federation message & auth server (backend for MyGNUHealth)"
description.fr = "Serveur de messages & d'authentification GNU Health (backend pour MyGNUHealth)"
version = "0.1.0~ynh1"
maintainers = ["garth-and-ai"]

[upstream]
license = "GPL-3.0-or-later"
website = "https://www.gnuhealth.org"
code = "https://savannah.gnu.org/projects/health/"
admindoc = "https://docs.gnuhealth.org/thalamus/"
userdoc = "https://docs.gnuhealth.org/mygnuhealth/"

[integration]
yunohost = ">= 12.0"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "300M"
ram.build = "200M"
ram.runtime = "100M"

[install]
  [install.domain]
  type = "domain"
  
  [install.path]
  type = "path"
  default = "/thalamus"

  [install.init_main_permission]
  type = "group"
  default = "all_users"  # accès privé recommandé pour des données sensibles

[resources]
  [resources.system_user]

  [resources.install_dir]

  [resources.permissions]
  main.url = "/"

  [resources.apt]
  packages = "python3, python3-venv, python3-pip, uwsgi, uwsgi-plugin-python3, postgresql, postgresql-contrib, build-essential, libpq-dev, ca-certificates"