#!/bin/bash
set -eu -o pipefail

# helpers YunoHost
source /usr/share/yunohost/helpers

# chemin absolu du dossier scripts/
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/_common.sh"

set -eu
source /usr/share/yunohost/helpers
source ./scripts/_common.sh

# Fichiers / conf
ynh_backup --src_path="$install_dir"
# Dump DB
ynh_psql_dump_db "$thalamus_db" > "$YNH_BACKUP_DIR/$app-postgres.sql"