#!/bin/bash
set -eu -o pipefail

# helpers YunoHost
source /usr/share/yunohost/helpers

# chemin absolu du dossier scripts/
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/_common.sh"

set -eu
source /usr/share/yunohost/helpers
source ./scripts/_common.sh

# Restaurer fichiers
ynh_restore_file --src_path="$install_dir"
# Restaurer DB
sudo -u postgres createdb -O "$app" "$thalamus_db" || true
sudo -u postgres psql "$thalamus_db" < "$YNH_BACKUP_DIR/$app-postgres.sql"

systemctl daemon-reload
systemctl enable --now "$app"